TrajectoryPlannerROS:
  max_vel_x: 1.2
  min_vel_x: 0.1
  max_rotational_vel: 0.6
  min_in_place_rotational_vel: 0.4
  backup_vel: 0.1

  acc_limit_th: .3
  acc_limit_x: 0.25
  acc_limit_y: 0

  holonomic_robot: false

  yaw_goal_tolerance: 1.57
  xy_goal_tolerance: 0.5
