local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05

observation_sources: base_laser1 front_sonar

base_laser1: {sensor_frame: base_laser1_link, data_type: LaserScan, topic: /harlie/base_laser1_scan, marking: true, clearing: true}
front_sonar: {sensor_frame: front_sonar, data_type: LaserScan, topic: /harlie/front_sonar_scan, marking: true, clearing: true}


