global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 200.0
  height: 200.0
  origin_x: 50.0
  origin_y: 50.0
  resolution: 0.05
