TrajectoryPlannerROS:
  max_vel_x: 1.2
  min_vel_x: 0.1
  max_rotational_vel: 0.6
  min_in_place_rotational_vel: 0.1

  acc_lim_th: 1.0
  acc_lim_x: 1.25
  acc_lim_y: 0

  holonomic_robot: false

  path_distance_bias: 0.8
  goal_distance_bias: 0.5
