TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_rotational_vel: 1.57
  min_in_place_rotational_vel: 0.1

  acc_lim_th: 0.1
  acc_lim_x: 0.1
  acc_lim_y: 0

  holonomic_robot: false

  #path_distance_bias: 0.8
  #goal_distance_bias: 0.5
